### PR TITLE
Apurvj

### PR DESCRIPTION
**Pull request by apurvj**
my first attempt on github

### CODE REVIEW

**Comment by raveesh-me** [comment]
got it

**Comment by apurvj** [comment]
okay.

**Comment by raveesh-me** [comment]
NICE POEM. After that it will be awesome if you recap the session. The steps involved were:
1. Asset Accumulation
2. First Screen
3. Making the Button Work
4. Navigator.push 
5. Make the second screen
6. Make a dummy route to see the second screen
7. Make a route generator that uses enum to generate properly configured routes
8. Make the last screens and complete the game with Navigator.pop()

**Comment by apurvj** [comment]
okay, so shall I add that and create one more pull request?

**Comment by raveesh-me** [comment]
just keep committing to the same branch

**Comment by apurvj** [comment]
committing to the branch done.

**Comment by raveesh-me** [comment]
do try to explain everything with your experience of the sesison. Try to be as helpful to someone coming on this repo for the first time.

Here are the images:
1. 
app screenshot

2.
app screenshot

3.  
app screenshot

4. 
app screenshot

**Comment by apurvj** [comment]
explaining about the content or how we built it? all the processes in brief?

**Comment by raveesh-me** [comment]
yes.

**Comment by apurvj** [comment]
Will this be enough?

**Comment by raveesh-me** [comment]
@apurvj congratulations on your first successful merge!

**Pull request merged**
